apis:
    - name: JSONPlaceholder - Posts
      url: https://jsonplaceholder.typicode.com/posts
      method: GET
    - name: JSONPlaceholder - Users
      url: https://jsonplaceholder.typicode.com/users
      method: GET
    - name: DummyJSON - Products
      url: https://dummyjson.com/products
      method: GET
    - name: DummyJSON - Auth Login
      url: https://dummyjson.com/auth/login
      method: POST
    - name: ReqRes - List Users
      url: https://reqres.in/api/users?page=2
      method: GET
    - name: ReqRes - Create User
      url: https://reqres.in/api/users
      method: POST
    - name: Cat Fact Ninja
      url: https://catfact.ninja/fact
      method: GET
    - name: Public APIs Health
      url: https://api.publicapis.org/entries
      method: GET
    - name: CoinDesk BPI
      url: https://api.coindesk.com/v1/bpi/currentprice.json
      method: GET
    - name: Dog CEO - Random Image
      url: https://dog.ceo/api/breeds/image/random
      method: GET
    - name: Agify - Age Predictor
      url: https://api.agify.io/?name=bella
      method: GET
    - name: Genderize - Predict
      url: https://api.genderize.io/?name=luc
      method: GET
    - name: Nationalize - Predict
      url: https://api.nationalize.io/?name=nathaniel
      method: GET
    - name: Zippopotam
      url: https://api.zippopotam.us/us/33162
      method: GET
    - name: Open Library - Books
      url: https://openlibrary.org/works/OL45804W.json
      method: GET
